version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  mongo: 
    image: mongo
    container_name: ahub-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME={MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD={MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-db:/data/db


  backend:
    command: npx prisma db pull --force
    build: .
    environment:
      - PORT=8080
      - DATABASE_URL={DATABASE_URL}
    depends_on:
      - mongo
  
  redis:
    image: redis
    container_name: ahub-redis
    environment:
      - REDIS_URL=redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com:10612
    

volumes:
  mongo-db:
      
