version: '3'
services:
  nginx:
    ports:
      - "8080:80"
  backend:
    build: 
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    command: npm start