version: '3'
services:
  nginx:
    ports:
      - "8080:80"
  backend:
    build: 
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=ahub_username
      - MONGO_PASSWORD=ahub_password
    command: npm run dev

  mongo: 
    environment:
      - MONGO_INITDB_ROOT_USERNAME=ahub_username
      - MONGO_INITDB_ROOT_PASSWORD=ahub_password
    