version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  mongo: 
    image: mongo
    container_name: ahub-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-db:/data/db


  backend:
    build: .
    environment:
      - PORT=8080
    depends_on:
      - mongo
  
  redis:
    image: redis
    container_name: ahub-redis
    

volumes:
  mongo-db:
      
