version: '3'
services:
  nginx:
    ports:
      - "8080:80"
  backend:
    build: 
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER={MONGO_USER}
      - MONGO_PASSWORD={MONGO_PASSWORD}
    command: npm run dev

  mongo: 
    environment:
      - MONGO_INITDB_ROOT_USERNAME={MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD={MONGO_INITDB_ROOT_PASSWORD}
    